# PerfTrack Version 1.0     September 1, 2005
# See PTLICENSE for distribution information.


all: bin lib

bin:
	cp PTdFgen.py ptGo.py build/ptbuild.py run/ptrun.py systemScan.py PERIxmlGen.py run/ptCNLfix.py $(prefix)/bin

lib:
	cp Application.py AttrVal.py Build.py Execution.py PTcommon.py PTexception.py PerfResult.py Resource.py ResourceIndex.py Run.py parsePerf.py parsePurple.py parseMilc.py toolParser.py Hardware.py PERIxml.py run/submission.py run/filesystem.py machine/gmLogger.py machine/gm_hs_tools.py machine/pt_proc.py machine/iMDL.py machine/ptdf.py machine/pt_xt4_proc.py $(prefix)/lib
